input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [message] {
    mutate {
      rename => { "message" => "log_message" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "biddex-logs-%{+YYYY.MM.dd}"
    ssl_enabled => false
  }
}
